# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ddb2797ea68a21c097f8b50afdeae6f314e4a94d00ca071e9f18823555031fd3517c5f2ecb2df363e6d90fb5b0401c03605100977f1c5d8446e20c8a98f8e21a

test:
  secret_key_base: 10d4c6a04981f2a8d77a524db3e69eb19feb8a11a6116883940c3476b8ae6a730dca9d1ed79f0caee99effa281f8bbfdc11ee1c3a43a82b6ca62324c8b64a052

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
